<a href="https://colab.research.google.com/github/njarambasophy17-glitch/Data-pre-processing-checkpoint/blob/main/Data_pre_processing_checkpoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv(r'STEG_BILLING_HISTORY.csv')

In [ ]:
df.head(10)

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11.0,1335667.0,0.0,203.0,8.0,1.0,82.0,0.0,0.0,0.0,14302.0,14384.0,4.0,ELEC
1,train_Client_0,2013-03-29,11.0,1335667.0,0.0,203.0,6.0,1.0,1200.0,184.0,0.0,0.0,12294.0,13678.0,4.0,ELEC
2,train_Client_0,2015-03-23,11.0,1335667.0,0.0,203.0,8.0,1.0,123.0,0.0,0.0,0.0,14624.0,14747.0,4.0,ELEC
3,train_Client_0,2015-07-13,11.0,1335667.0,0.0,207.0,8.0,1.0,102.0,0.0,0.0,0.0,14747.0,14849.0,4.0,ELEC
4,train_Client_0,2016-11-17,11.0,1335667.0,0.0,207.0,9.0,1.0,572.0,0.0,0.0,0.0,15066.0,15638.0,12.0,ELEC
5,train_Client_0,2017-07-17,11.0,1335667.0,0.0,207.0,9.0,1.0,314.0,0.0,0.0,0.0,15638.0,15952.0,8.0,ELEC
6,train_Client_0,2018-12-07,11.0,1335667.0,0.0,207.0,9.0,1.0,541.0,0.0,0.0,0.0,15952.0,16493.0,12.0,ELEC
7,train_Client_0,2019-03-19,11.0,1335667.0,0.0,207.0,9.0,1.0,585.0,0.0,0.0,0.0,16493.0,17078.0,8.0,ELEC
8,train_Client_0,2011-07-22,11.0,1335667.0,0.0,203.0,9.0,1.0,1200.0,186.0,0.0,0.0,7770.0,9156.0,4.0,ELEC
9,train_Client_0,2011-11-22,11.0,1335667.0,0.0,203.0,6.0,1.0,1082.0,0.0,0.0,0.0,9156.0,10238.0,4.0,ELEC

In [ ]:
client_0_bills = df.head(10)

In [ ]:
print(type(client_0_bills))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
df.shape

(656464, 16)

In [ ]:
df.info() # shows missing values from all, except 'client_id'
                #memory usage  61.3+ MB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 656464 entries, 0 to 656463
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   client_id             656464 non-null  object
 1   invoice_date          656463 non-null  object
 2   tarif_type            656463 non-null  float64
 3   counter_number        656456 non-null  float64
 4   counter_statue        656463 non-null  float64
 5   counter_code          656463 non-null  float64
 6   reading_remarque      655796 non-null  float64
 7   counter_coefficient   656463 non-null  float64
 8   consommation_level_1  656463 non-null  float64
 9   consommation_level_2  656463 non-null  float64
 10  consommation_level_3  656463 non-null  float64
 11  consommation_level_4  656463 non-null  float64
 12  old_index             656463 non-null  float64
 13  new_index             656463 non-null  float64
 14  months_number         656463 non-null  float64
 15  counter_type          656463 non-null  object
dtypes: float64(13), object(3)
memory usage: 80.1+ MB

In [ ]:
df.describe()

,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number
count,656463.000000,6.564560e+05,656463.000000,656463.000000,655796.000000,656463.000000,656463.000000,656463.000000,656463.000000,656463.000000,6.564630e+05,6.564630e+05,656463.000000
mean,20.135673,1.148048e+11,0.042004,171.768182,7.321460,1.000049,406.884833,109.857806,20.558679,53.428470,1.749713e+04,1.805799e+04,26.355799
std,13.473841,1.598770e+12,0.374082,133.201630,1.361014,0.018055,570.172259,1369.040566,181.330521,1027.304049,4.040745e+04,4.098385e+04,1590.157791
min,8.000000,0.000000e+00,0.000000,5.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,1.000000
25%,11.000000,1.232420e+05,0.000000,5.000000,6.000000,1.000000,79.000000,0.000000,0.000000,0.000000,1.777000e+03,2.046000e+03,4.000000
50%,11.000000,4.949770e+05,0.000000,203.000000,8.000000,1.000000,272.000000,0.000000,0.000000,0.000000,7.612000e+03,8.112000e+03,4.000000
75%,40.000000,1.115579e+06,0.000000,207.000000,9.000000,1.000000,600.000000,0.000000,0.000000,0.000000,2.157000e+04,2.224800e+04,4.000000
max,45.000000,2.738110e+13,5.000000,600.000000,9.000000,10.000000,93385.000000,819886.000000,45360.000000,343568.000000,2.800280e+06,2.870972e+06,231602.000000

In [ ]:
df = df.fillna(df.median(numeric_only=True))

# Handle missing invoice_date (object type) by converting to datetime and filling with mode
df['invoice_date'] = pd.to_datetime(df['invoice_date'], errors='coerce')
if df['invoice_date'].isnull().any():
    most_common_date = df['invoice_date'].mode()[0]
    df['invoice_date'] = df['invoice_date'].fillna(most_common_date)

# Handle missing counter_type (object type) by filling with mode
if df['counter_type'].isnull().any():
    most_common_counter_type = df['counter_type'].mode()[0]
    df['counter_type'] = df['counter_type'].fillna(most_common_counter_type)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 656464 entries, 0 to 656463
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   client_id             656464 non-null  object
 1   invoice_date          656464 non-null  datetime64[ns]
 2   tarif_type            656464 non-null  float64
 3   counter_number        656464 non-null  float64
 4   counter_code          656464 non-null  float64
 5   reading_remarque      656464 non-null  float64
 6   counter_coefficient   656464 non-null  float64
 7   consommation_level_1  656464 non-null  float64
 8   consommation_level_2  656464 non-null  float64
 9   consommation_level_3  656464 non-null  float64
 10  consommation_level_4  656464 non-null  float64
 11  old_index             656464 non-null  float64
 12  new_index             656464 non-null  float64
 13  months_number         656464 non-null  float64
 14  counter_type          656464 non-null  object
 15  counter_type_encoded  656464 non-null  int64
dtypes: datetime64[ns](1), float64(12), int64(1), object(2)
memory usage: 80.1+ MB

In [ ]:
client_0_bills = df[df['client_id'] == 'train_Client_0']
print(client_0_bills)

         client_id invoice_date  tarif_type  counter_number  counter_statue  \
0   train_Client_0   2014-03-24        11.0       1335667.0             0.0
1   train_Client_0   2013-03-29        11.0       1335667.0             0.0
2   train_Client_0   2015-03-23        11.0       1335667.0             0.0
3   train_Client_0   2015-07-13        11.0       1335667.0             0.0
4   train_Client_0   2016-11-17        11.0       1335667.0             0.0
5   train_Client_0   2017-07-17        11.0       1335667.0             0.0
6   train_Client_0   2018-12-07        11.0       1335667.0             0.0
7   train_Client_0   2019-03-19        11.0       1335667.0             0.0
8   train_Client_0   2011-07-22        11.0       1335667.0             0.0
9   train_Client_0   2011-11-22        11.0       1335667.0             0.0
10  train_Client_0   2008-11-25        11.0       1335667.0             0.0
11  train_Client_0   2012-07-23        11.0       1335667.0             0.0
12  train_Client_0   2012-11-29        11.0       1335667.0             0.0
13  train_Client_0   2013-07-22        11.0       1335667.0             0.0
14  train_Client_0   2014-07-18        11.0       1335667.0             0.0
15  train_Client_0   2014-11-24        11.0       1335667.0             0.0
16  train_Client_0   2015-11-18        11.0       1335667.0             0.0
17  train_Client_0   2012-03-27        11.0       1335667.0             0.0
18  train_Client_0   2011-03-30        11.0       1335667.0             0.0
19  train_Client_0   2013-02-12        11.0       1335667.0             0.0
20  train_Client_0   2010-07-22        11.0       1335667.0             0.0
21  train_Client_0   2010-11-24        11.0       1335667.0             0.0
22  train_Client_0   2005-10-17        11.0       1335667.0             0.0
23  train_Client_0   2006-02-24        11.0       1335667.0             0.0
24  train_Client_0   2006-06-23        11.0       1335667.0             0.0
25  train_Client_0   2006-10-18        11.0       1335667.0             0.0
26  train_Client_0   2007-06-27        11.0       1335667.0             0.0
27  train_Client_0   2007-10-25        11.0       1335667.0             0.0
28  train_Client_0   2007-02-26        11.0       1335667.0             0.0
29  train_Client_0   2008-07-28        11.0       1335667.0             0.0
30  train_Client_0   2009-01-04        11.0       1335667.0             0.0
31  train_Client_0   2009-07-27        11.0       1335667.0             0.0
32  train_Client_0   2009-11-24        11.0       1335667.0             0.0
33  train_Client_0   2010-03-29        11.0       1335667.0             0.0
34  train_Client_0   2008-01-04        11.0       1335667.0             0.0

    counter_code  reading_remarque  counter_coefficient  consommation_level_1  \
0          203.0               8.0                  1.0                  82.0
1          203.0               6.0                  1.0                1200.0
2          203.0               8.0                  1.0                 123.0
3          207.0               8.0                  1.0                 102.0
4          207.0               9.0                  1.0                 572.0
5          207.0               9.0                  1.0                 314.0
6          207.0               9.0                  1.0                 541.0
7          207.0               9.0                  1.0                 585.0
8          203.0               9.0                  1.0                1200.0
9          203.0               6.0                  1.0                1082.0
10         203.0               6.0                  1.0                 174.0
11         203.0               6.0                  1.0                 628.0
12         203.0               6.0                  1.0                 886.0
13         203.0               8.0                  1.0                 147.0
14         203.0               8.0                  1.0                  99.0
15         203.0               8.0                  1.0                 141.0
16         207.0               9.0                  1.0                 217.0
17         203.0               8.0                  1.0                 292.0
18         203.0               6.0                  1.0                 497.0
19         203.0               8.0                  1.0                  38.0
20         203.0               6.0                  1.0                 278.0
21         203.0               6.0                  1.0                 234.0
22         203.0               6.0                  1.0                 124.0
23         203.0               6.0                  1.0                 141.0
24         203.0               6.0                  1.0                 162.0
25         203.0               6.0                  1.0                 159.0
26         203.0               6.0                  1.0                 240.0
27         203.0               6.0                  1.0                 276.0
28         203.0               6.0                  1.0                 182.0
29         203.0               6.0                  1.0                 171.0
30         203.0               6.0                  1.0                 315.0
31         203.0               6.0                  1.0                 312.0
32         203.0               6.0                  1.0                 267.0
33         203.0               6.0                  1.0                 276.0
34         203.0               6.0                  1.0                 277.0

    consommation_level_2  consommation_level_3  consommation_level_4  \
0                    0.0                   0.0                   0.0
1                  184.0                   0.0                   0.0
2                    0.0                   0.0                   0.0
3                    0.0                   0.0                   0.0
4                    0.0                   0.0                   0.0
5                    0.0                   0.0                   0.0
6                    0.0                   0.0                   0.0
7                    0.0                   0.0                   0.0
8                  186.0                   0.0                   0.0
9                    0.0                   0.0                   0.0
10                   0.0                   0.0                   0.0
11                   0.0                   0.0                   0.0
12                   0.0                   0.0                   0.0
13                   0.0                   0.0                   0.0
14                   0.0                   0.0                   0.0
15                   0.0                   0.0                   0.0
16                   0.0                   0.0                   0.0
17                   0.0                   0.0                   0.0
18                   0.0                   0.0                   0.0
19                   0.0                   0.0                   0.0
20                   0.0                   0.0                   0.0
21                   0.0                   0.0                   0.0
22                   0.0                   0.0                   0.0
23                   0.0                   0.0                   0.0
24                   0.0                   0.0                   0.0
25                   0.0                   0.0                   0.0
26                   0.0                   0.0                   0.0
27                   0.0                   0.0                   0.0
28                   0.0                   0.0                   0.0
29                   0.0                   0.0                   0.0
30                   0.0                   0.0                   0.0
31                   0.0                   0.0                   0.0
32                   0.0                   0.0                   0.0
33                   0.0                   0.0                   0.0
34                   0.0                   0.0                   0.0

    old_index  new_index  months_number counter_type
0     14302.0    14384.0            4.0         ELEC
1     12294.0    13678.0            4.0         ELEC
2     14624.0    14747.0            4.0         ELEC
3     14747.0    14849.0            4.0         ELEC
4     15066.0    15638.0           12.0         ELEC
5     15638.0    15952.0            8.0         ELEC
6     15952.0    16493.0           12.0         ELEC
7     16493.0    17078.0            8.0         ELEC
8      7770.0     9156.0            4.0         ELEC
9      9156.0    10238.0            4.0         ELEC
10     5417.0     5591.0            4.0         ELEC
11    10780.0    11408.0            4.0         ELEC
12    11408.0    12294.0            4.0         ELEC
13    13983.0    14130.0            4.0         ELEC
14    14384.0    14483.0            4.0         ELEC
15    14483.0    14624.0            4.0         ELEC
16    14849.0    15066.0            4.0         ELEC
17    10488.0    10780.0            4.0         ELEC
18     7273.0     7770.0            4.0         ELEC
19    14264.0    14302.0            2.0         ELEC
20     6761.0     7039.0            4.0         ELEC
21     7039.0     7273.0            4.0         ELEC
22     3685.0     3809.0            4.0         ELEC
23     3809.0     3950.0            4.0         ELEC
24     3950.0     4112.0            4.0         ELEC
25     4112.0     4271.0            4.0         ELEC
26     4453.0     4693.0            4.0         ELEC
27     4693.0     4969.0            4.0         ELEC
28     4271.0     4453.0            4.0         ELEC
29     5246.0     5417.0            4.0         ELEC
30     5591.0     5906.0            4.0         ELEC
31     5906.0     6218.0            4.0         ELEC
32     6218.0     6485.0            4.0         ELEC
33     6485.0     6761.0            4.0         ELEC
34     4969.0     5246.0            4.0         ELEC

In [ ]:
# Second method to select bills for client 'train_Client_0' using .query()
client_0_bills_query = df.query('client_id == "train_Client_0"')
print("\nClient 'train_Client_0' bills (Method 2 - using .query()):")
print(client_0_bills_query)

Client 'train_Client_0' bills (Method 2 - using .query()):
         client_id invoice_date  tarif_type  counter_number  counter_code  \
0   train_Client_0   2014-03-24        11.0       1335667.0         203.0
1   train_Client_0   2013-03-29        11.0       1335667.0         203.0
2   train_Client_0   2015-03-23        11.0       1335667.0         203.0
3   train_Client_0   2015-07-13        11.0       1335667.0         207.0
4   train_Client_0   2016-11-17        11.0       1335667.0         207.0
5   train_Client_0   2017-07-17        11.0       1335667.0         207.0
6   train_Client_0   2018-12-07        11.0       1335667.0         207.0
7   train_Client_0   2019-03-19        11.0       1335667.0         207.0
8   train_Client_0   2011-07-22        11.0       1335667.0         203.0
9   train_Client_0   2011-11-22        11.0       1335667.0         203.0
10  train_Client_0   2008-11-25        11.0       1335667.0         203.0
11  train_Client_0   2012-07-23        11.0       1335667.0         203.0
12  train_Client_0   2012-11-29        11.0       1335667.0         203.0
13  train_Client_0   2013-07-22        11.0       1335667.0         203.0
14  train_Client_0   2014-07-18        11.0       1335667.0         203.0
15  train_Client_0   2014-11-24        11.0       1335667.0         203.0
16  train_Client_0   2015-11-18        11.0       1335667.0         207.0
17  train_Client_0   2012-03-27        11.0       1335667.0         203.0
18  train_Client_0   2011-03-30        11.0       1335667.0         203.0
19  train_Client_0   2013-02-12        11.0       1335667.0         203.0
20  train_Client_0   2010-07-22        11.0       1335667.0         203.0
21  train_Client_0   2010-11-24        11.0       1335667.0         203.0
22  train_Client_0   2005-10-17        11.0       1335667.0         203.0
23  train_Client_0   2006-02-24        11.0       1335667.0         203.0
24  train_Client_0   2006-06-23        11.0       1335667.0         203.0
25  train_Client_0   2006-10-18        11.0       1335667.0         203.0
26  train_Client_0   2007-06-27        11.0       1335667.0         203.0
27  train_Client_0   2007-10-25        11.0       1335667.0         203.0
28  train_Client_0   2007-02-26        11.0       1335667.0         203.0
29  train_Client_0   2008-07-28        11.0       1335667.0         203.0
30  train_Client_0   2009-01-04        11.0       1335667.0         203.0
31  train_Client_0   2009-07-27        11.0       1335667.0         203.0
32  train_Client_0   2009-11-24        11.0       1335667.0         203.0
33  train_Client_0   2010-03-29        11.0       1335667.0         203.0
34  train_Client_0   2008-01-04        11.0       1335667.0         203.0

    reading_remarque  counter_coefficient  consommation_level_1  \
0                8.0                  1.0                  82.0
1                6.0                  1.0                1200.0
2                8.0                  1.0                 123.0
3                8.0                  1.0                 102.0
4                9.0                  1.0                 572.0
5                9.0                  1.0                 314.0
6                9.0                  1.0                 541.0
7                9.0                  1.0                 585.0
8                9.0                  1.0                1200.0
9                6.0                  1.0                1082.0
10               6.0                  1.0                 174.0
11               6.0                  1.0                 628.0
12               6.0                  1.0                 886.0
13               8.0                  1.0                 147.0
14               8.0                  1.0                  99.0
15               8.0                  1.0                 141.0
16               9.0                  1.0                 217.0
17               8.0                  1.0                 292.0
18               6.0                  1.0                 497.0
19               8.0                  1.0                  38.0
20               6.0                  1.0                 278.0
21               6.0                  1.0                 234.0
22               6.0                  1.0                 124.0
23               6.0                  1.0                 141.0
24               6.0                  1.0                 162.0
25               6.0                  1.0                 159.0
26               6.0                  1.0                 240.0
27               6.0                  1.0                 276.0
28               6.0                  1.0                 182.0
29               6.0                  1.0                 171.0
30               6.0                  1.0                 315.0
31               6.0                  1.0                 312.0
32               6.0                  1.0                 267.0
33               6.0                  1.0                 276.0
34               6.0                  1.0                 277.0

    consommation_level_2  consommation_level_3  consommation_level_4  \
0                    0.0                   0.0                   0.0
1                  184.0                   0.0                   0.0
2                    0.0                   0.0                   0.0
3                    0.0                   0.0                   0.0
4                    0.0                   0.0                   0.0
5                    0.0                   0.0                   0.0
6                    0.0                   0.0                   0.0
7                    0.0                   0.0                   0.0
8                  186.0                   0.0                   0.0
9                    0.0                   0.0                   0.0
10                   0.0                   0.0                   0.0
11                   0.0                   0.0                   0.0
12                   0.0                   0.0                   0.0
13                   0.0                   0.0                   0.0
14                   0.0                   0.0                   0.0
15                   0.0                   0.0                   0.0
16                   0.0                   0.0                   0.0
17                   0.0                   0.0                   0.0
18                   0.0                   0.0                   0.0
19                   0.0                   0.0                   0.0
20                   0.0                   0.0                   0.0
21                   0.0                   0.0                   0.0
22                   0.0                   0.0                   0.0
23                   0.0                   0.0                   0.0
24                   0.0                   0.0                   0.0
25                   0.0                   0.0                   0.0
26                   0.0                   0.0                   0.0
27                   0.0                   0.0                   0.0
28                   0.0                   0.0                   0.0
29                   0.0                   0.0                   0.0
30                   0.0                   0.0                   0.0
31                   0.0                   0.0                   0.0
32                   0.0                   0.0                   0.0
33                   0.0                   0.0                   0.0
34                   0.0                   0.0                   0.0

    old_index  new_index  months_number counter_type  counter_type_encoded
0     14302.0    14384.0            4.0         ELEC                     0
1     12294.0    13678.0            4.0         ELEC                     0
2     14624.0    14747.0            4.0         ELEC                     0
3     14747.0    14849.0            4.0         ELEC                     0
4     15066.0    15638.0           12.0         ELEC                     0
5     15638.0    15952.0            8.0         ELEC                     0
6     15952.0    16493.0           12.0         ELEC                     0
7     16493.0    17078.0            8.0         ELEC                     0
8      7770.0     9156.0            4.0         ELEC                     0
9      9156.0    10238.0            4.0         ELEC                     0
10     5417.0     5591.0            4.0         ELEC                     0
11    10780.0    11408.0            4.0         ELEC                     0
12    11408.0    12294.0            4.0         ELEC                     0
13    13983.0    14130.0            4.0         ELEC                     0
14    14384.0    14483.0            4.0         ELEC                     0
15    14483.0    14624.0            4.0         ELEC                     0
16    14849.0    15066.0            4.0         ELEC                     0
17    10488.0    10780.0            4.0         ELEC                     0
18     7273.0     7770.0            4.0         ELEC                     0
19    14264.0    14302.0            2.0         ELEC                     0
20     6761.0     7039.0            4.0         ELEC                     0
21     7039.0     7273.0            4.0         ELEC                     0
22     3685.0     3809.0            4.0         ELEC                     0
23     3809.0     3950.0            4.0         ELEC                     0
24     3950.0     4112.0            4.0         ELEC                     0
25     4112.0     4271.0            4.0         ELEC                     0
26     4453.0     4693.0            4.0         ELEC                     0
27     4693.0     4969.0            4.0         ELEC                     0
28     4271.0     4453.0            4.0         ELEC                     0
29     5246.0     5417.0            4.0         ELEC                     0
30     5591.0     5906.0            4.0         ELEC                     0
31     5906.0     6218.0            4.0         ELEC                     0
32     6218.0     6485.0            4.0         ELEC                     0
33     6485.0     6761.0            4.0         ELEC                     0
34     4969.0     5246.0            4.0         ELEC                     0

In [ ]:
#Transform the 'counter_type' feature to a numeric variable using the encoder of your choice.

le = LabelEncoder()
df['counter_type_encoded'] = le.fit_transform(df['counter_type'])
print(df[['counter_type', 'counter_type_encoded']].head())

  counter_type  counter_type_encoded
0         ELEC                     0
1         ELEC                     0
2         ELEC                     0
3         ELEC                     0
4         ELEC                     0

In [ ]:
#Delete the 'counter_statue' feature from the Dataframe

df.drop('counter_statue', axis=1, inplace=True)
print(df.columns)

Index(['client_id', 'invoice_date', 'tarif_type', 'counter_number',
       'counter_code', 'reading_remarque', 'counter_coefficient',
       'consommation_level_1', 'consommation_level_2', 'consommation_level_3',
       'consommation_level_4', 'old_index', 'new_index', 'months_number',
       'counter_type', 'counter_type_encoded'],
      dtype='object')